# Generated by Django 6.0.4 on 2026-04-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
